<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'cover_image' => 'the-great-gatsby.jpg',
                'title' => 'The Great Gatsby',
                'author_id' => 8,
                'publisher_id' => 1,
                'publish_year' => 1925,
                'language' => 'English',
                'location' => 'Rak A1',
                'category_id' => 1,
                'call_number' => 'FIC FIT 001',
                'isbn' => '9780743273565',
                'pages' => '180',
                'description' => 'A classic novel about ambition, wealth, and longing in the Jazz Age.',
                'edition' => 'First Edition',
                'stock' => '5',
            ],
            [
                'cover_image' => 'pride-and-prejudice.jpg',
                'title' => 'Pride and Prejudice',
                'author_id' => 5,
                'publisher_id' => 2,
                'publish_year' => 1950,
                'language' => 'English',
                'location' => 'Rak A2',
                'category_id' => 1,
                'call_number' => 'FIC AUS 002',
                'isbn' => '9780141439518',
                'pages' => '432',
                'description' => 'A romantic novel about manners, family, and social expectations.',
                'edition' => 'Revised Edition',
                'stock' => '4',
            ],
            [
                'cover_image' => 'sapiens.jpg',
                'title' => 'Sapiens: A Brief History of Humankind',
                'author_id' => 7,
                'publisher_id' => 3,
                'publish_year' => 2011,
                'language' => 'English',
                'location' => 'Rak B1',
                'category_id' => 2,
                'call_number' => 'NON HEM 003',
                'isbn' => '9780062316097',
                'pages' => '464',
                'description' => 'An accessible overview of human development from early societies to modern life.',
                'edition' => 'International Edition',
                'stock' => '6',
            ],
            [
                'cover_image' => 'atomic-habits.jpg',
                'title' => 'Atomic Habits',
                'author_id' => 6,
                'publisher_id' => 4,
                'publish_year' => 2018,
                'language' => 'English',
                'location' => 'Rak B2',
                'category_id' => 2,
                'call_number' => 'NON TWA 004',
                'isbn' => '9780735211292',
                'pages' => '320',
                'description' => 'A practical guide to building good habits and breaking bad ones.',
                'edition' => 'First Edition',
                'stock' => '8',
            ],
            [
                'cover_image' => 'dune.jpg',
                'title' => 'Dune',
                'author_id' => 2,
                'publisher_id' => 5,
                'publish_year' => 1965,
                'language' => 'English',
                'location' => 'Rak C1',
                'category_id' => 3,
                'call_number' => 'SCI MAR 005',
                'isbn' => '9780441172719',
                'pages' => '688',
                'description' => 'A science fiction epic about politics, ecology, and destiny on a desert planet.',
                'edition' => 'Anniversary Edition',
                'stock' => '3',
            ],
            [
                'cover_image' => 'foundation.jpg',
                'title' => 'Foundation',
                'author_id' => 9,
                'publisher_id' => 1,
                'publish_year' => 1951,
                'language' => 'English',
                'location' => 'Rak C2',
                'category_id' => 3,
                'call_number' => 'SCI MUR 006',
                'isbn' => '9780553293357',
                'pages' => '255',
                'description' => 'A story of science, empire, and the effort to preserve knowledge.',
                'edition' => 'Classic Edition',
                'stock' => '4',
            ],
            [
                'cover_image' => 'harry-potter-sorcerers-stone.jpg',
                'title' => 'Harry Potter and the Sorcerer\'s Stone',
                'author_id' => 1,
                'publisher_id' => 6,
                'publish_year' => 1997,
                'language' => 'English',
                'location' => 'Rak D1',
                'category_id' => 4,
                'call_number' => 'FAN ROW 007',
                'isbn' => '9780590353427',
                'pages' => '309',
                'description' => 'A young wizard begins his journey at a magical school.',
                'edition' => 'Paperback Edition',
                'stock' => '10',
            ],
            [
                'cover_image' => 'game-of-thrones.jpg',
                'title' => 'A Game of Thrones',
                'author_id' => 2,
                'publisher_id' => 7,
                'publish_year' => 1996,
                'language' => 'English',
                'location' => 'Rak D2',
                'category_id' => 4,
                'call_number' => 'FAN MAR 008',
                'isbn' => '9780553103540',
                'pages' => '694',
                'description' => 'A fantasy novel of noble houses, power struggles, and ancient threats.',
                'edition' => 'First Edition',
                'stock' => '5',
            ],
            [
                'cover_image' => 'murder-on-orient-express.jpg',
                'title' => 'Murder on the Orient Express',
                'author_id' => 3,
                'publisher_id' => 2,
                'publish_year' => 1934,
                'language' => 'English',
                'location' => 'Rak E1',
                'category_id' => 5,
                'call_number' => 'MYS CHR 009',
                'isbn' => '9780062693662',
                'pages' => '256',
                'description' => 'Detective Hercule Poirot investigates a murder aboard a luxury train.',
                'edition' => 'Reprint Edition',
                'stock' => '7',
            ],
            [
                'cover_image' => 'and-then-there-were-none.jpg',
                'title' => 'And Then There Were None',
                'author_id' => 3,
                'publisher_id' => 3,
                'publish_year' => 1939,
                'language' => 'English',
                'location' => 'Rak E2',
                'category_id' => 5,
                'call_number' => 'MYS CHR 010',
                'isbn' => '9780062073488',
                'pages' => '272',
                'description' => 'Ten strangers are invited to an isolated island where secrets turn deadly.',
                'edition' => 'Paperback Edition',
                'stock' => '6',
            ],
            [
                'cover_image' => 'steve-jobs.jpg',
                'title' => 'Steve Jobs',
                'author_id' => 10,
                'publisher_id' => 4,
                'publish_year' => 2011,
                'language' => 'English',
                'location' => 'Rak F1',
                'category_id' => 6,
                'call_number' => 'BIO ALL 011',
                'isbn' => '9781451648539',
                'pages' => '656',
                'description' => 'A biography about the life, work, and influence of Steve Jobs.',
                'edition' => 'First Edition',
                'stock' => '4',
            ],
            [
                'cover_image' => 'becoming.jpg',
                'title' => 'Becoming',
                'author_id' => 10,
                'publisher_id' => 5,
                'publish_year' => 2018,
                'language' => 'English',
                'location' => 'Rak F2',
                'category_id' => 6,
                'call_number' => 'BIO ALL 012',
                'isbn' => '9781524763138',
                'pages' => '448',
                'description' => 'A memoir about identity, public service, and personal growth.',
                'edition' => 'First Edition',
                'stock' => '5',
            ],
            [
                'cover_image' => 'guns-germs-steel.jpg',
                'title' => 'Guns, Germs, and Steel',
                'author_id' => 7,
                'publisher_id' => 1,
                'publish_year' => 1997,
                'language' => 'English',
                'location' => 'Rak G1',
                'category_id' => 7,
                'call_number' => 'HIS HEM 013',
                'isbn' => '9780393317558',
                'pages' => '480',
                'description' => 'A historical analysis of geography, society, and global development.',
                'edition' => 'Updated Edition',
                'stock' => '3',
            ],
            [
                'cover_image' => 'a-brief-history-of-time.jpg',
                'title' => 'A Brief History of Time',
                'author_id' => 9,
                'publisher_id' => 2,
                'publish_year' => 1988,
                'language' => 'English',
                'location' => 'Rak G2',
                'category_id' => 7,
                'call_number' => 'HIS MUR 014',
                'isbn' => '9780553380163',
                'pages' => '212',
                'description' => 'An introduction to cosmology, time, and the nature of the universe.',
                'edition' => 'Updated Edition',
                'stock' => '5',
            ],
            [
                'cover_image' => 'charlottes-web.jpg',
                'title' => 'Charlotte\'s Web',
                'author_id' => 6,
                'publisher_id' => 6,
                'publish_year' => 1952,
                'language' => 'English',
                'location' => 'Rak H1',
                'category_id' => 8,
                'call_number' => 'CHI TWA 015',
                'isbn' => '9780061124952',
                'pages' => '192',
                'description' => 'A children\'s story about friendship, courage, and kindness.',
                'edition' => 'Illustrated Edition',
                'stock' => '9',
            ],
            [
                'cover_image' => 'the-little-prince.jpg',
                'title' => 'The Little Prince',
                'author_id' => 5,
                'publisher_id' => 7,
                'publish_year' => 1943,
                'language' => 'English',
                'location' => 'Rak H2',
                'category_id' => 8,
                'call_number' => 'CHI AUS 016',
                'isbn' => '9780156012195',
                'pages' => '96',
                'description' => 'A poetic tale about childhood, imagination, and seeing with the heart.',
                'edition' => 'Classic Edition',
                'stock' => '8',
            ],
            [
                'cover_image' => 'norwegian-wood.jpg',
                'title' => 'Norwegian Wood',
                'author_id' => 9,
                'publisher_id' => 1,
                'publish_year' => 1987,
                'language' => 'English',
                'location' => 'Rak A3',
                'category_id' => 1,
                'call_number' => 'FIC MUR 017',
                'isbn' => '9780375704024',
                'pages' => '296',
                'description' => 'A reflective novel about memory, love, and loss.',
                'edition' => 'Vintage Edition',
                'stock' => '4',
            ],
            [
                'cover_image' => 'it.jpg',
                'title' => 'It',
                'author_id' => 4,
                'publisher_id' => 2,
                'publish_year' => 1986,
                'language' => 'English',
                'location' => 'Rak E3',
                'category_id' => 5,
                'call_number' => 'MYS KIN 018',
                'isbn' => '9781501142970',
                'pages' => '1168',
                'description' => 'A suspenseful story about childhood fears returning in terrifying form.',
                'edition' => 'Reprint Edition',
                'stock' => '2',
            ],
            [
                'cover_image' => 'the-old-man-and-the-sea.jpg',
                'title' => 'The Old Man and the Sea',
                'author_id' => 7,
                'publisher_id' => 3,
                'publish_year' => 1952,
                'language' => 'English',
                'location' => 'Rak A4',
                'category_id' => 1,
                'call_number' => 'FIC HEM 019',
                'isbn' => '9780684801223',
                'pages' => '128',
                'description' => 'A short novel about endurance, dignity, and struggle at sea.',
                'edition' => 'Classic Edition',
                'stock' => '6',
            ],
            [
                'cover_image' => 'house-of-the-spirits.jpg',
                'title' => 'The House of the Spirits',
                'author_id' => 10,
                'publisher_id' => 4,
                'publish_year' => 1982,
                'language' => 'English',
                'location' => 'Rak D3',
                'category_id' => 4,
                'call_number' => 'FAN ALL 020',
                'isbn' => '9781501117015',
                'pages' => '448',
                'description' => 'A multigenerational story blending family history and magical realism.',
                'edition' => 'Paperback Edition',
                'stock' => '5',
            ],
        ];

        foreach ($books as $book){
            Book::create($book);
        }
    }
}
